import{loadFighter,drawSprite,sequences}from'./sprites-v6.js';
import{Arena,CONTROL,STAGE_DEFS,resolveStageUrl}from'./arena-v6.js';
const $=x=>document.getElementById(x),grid=$('fighterGrid'),assets=new Map(),arena=new Arena($('gameCanvas'),hud,sound);
const tags={'neon-laneway-beatdown':'MELBOURNE / NIGHT','backyard-bbq-bash':'AUSSIE SUBURB / SUNSET','construction-yard-throwdown':'CITY BUILD / SUNSET','arcade-food-court-frenzy':'MALL ARCADE / NEON','docklands-container-clash':'PORT / MIDNIGHT','outback-servo-showdown':'OUTBACK / GOLDEN HOUR'},stages=STAGE_DEFS.map(x=>({...x,tag:tags[x.id]}));
const timing={idle:90,walk:84,jump:70,crouch:56,punch:58,kick:64,special:72,hurt:48,block:52,fall:68,getup:68,victory:96},cycle=sequences.reduce((a,s)=>a+timing[s],0);
let roster=[],pick=['douchebag-dave','bimbo-babe'],slot=0,mode='cpu',stage='neon-laneway-beatdown',muted=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,tick=0,labTick=0,labPlay=true,audio;
try{let s={...JSON.parse(localStorage.getItem('sf-v5')||'{}'),...JSON.parse(localStorage.getItem('sf-v6')||'{}')};muted=!!s.muted;reduced=typeof s.reduced==='boolean'?s.reduced:reduced;if(s.stage==='random'||stages.some(x=>x.id===s.stage))stage=s.stage}catch{}
function save(){try{localStorage.setItem('sf-v6',JSON.stringify({muted,reduced,stage}))}catch{}}
function sound(f=300,d=.03){if(muted)return;try{audio||=new(window.AudioContext||window.webkitAudioContext);audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=f;g.gain.value=.045;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function ready(id){return assets.get(id)?.status==='ready'}
function setting(){arena.reduced=reduced;document.body.classList.toggle('reduced',reduced);$('motionButton').textContent='REDUCED MOTION: '+(reduced?'ON':'OFF');$('muteButton').textContent='SOUND '+(muted?'OFF':'ON')}
function choose(id,n=slot){pick[n]=id;slot=n;sync();sound(370,.025)}
function stageDef(){return stages.find(x=>x.id===stage)}
function syncStage(){let d=stageDef(),name=d?.name||'Random Stage';$('stageChoice').textContent=$('venueName').textContent=name;for(let b of $('stageGrid').children)b.setAttribute('aria-pressed',b.dataset.stage===stage)}
function sync(){
 for(let i=0;i<2;i++){let d=roster.find(x=>x.id===pick[i]);if(!d)continue;let p=$('preview'+i);p.classList.toggle('active',slot===i);p.querySelector('.slot-head').setAttribute('aria-pressed',slot===i);p.querySelector('em').textContent=slot===i?'SELECTING':'CHANGE';p.querySelector('h2').textContent=d.name;p.querySelector('.country').textContent=d.country;p.querySelector('.archetype').textContent=d.style;p.querySelector('.bio').textContent=d.bio;p.querySelector('.signature strong').textContent=d.special;let m=p.querySelectorAll('meter');m[0].value=d.speed||1;m[1].value=d.defense||1}
 for(let b of grid.children){let id=b.dataset.id;b.classList.toggle('chosen1',pick[0]===id);b.classList.toggle('chosen2',pick[1]===id);b.querySelector('[data-badge="0"]').hidden=pick[0]!==id;b.querySelector('[data-badge="1"]').hidden=pick[1]!==id}
 $('assignLabel').textContent='ASSIGNING TO P'+(slot+1);$('summaryNames').textContent=pick.map(id=>roster.find(x=>x.id===id)?.name||'Loading').join('  / VS /  ');let ok=pick.every(ready);$('startButton').disabled=!ok;$('startButton').textContent=ok?(mode==='training'?'START PRACTICE  ↗':"LET'S FIGHT  ↗"):'LOADING ARTWORK...';$('opponentLabel').textContent=mode==='cpu'?'CPU OPPONENT':mode==='training'?'TRAINING PARTNER':'PLAYER 2';$('difficultyLabel').hidden=mode!=='cpu';$('rulesLabel').textContent=mode==='training'?'Unlimited practice':'First to 2 rounds';$('rulesLabel').nextElementSibling.textContent=mode==='training'?'Full special meter':'60 second clock';let good=roster.filter(x=>ready(x.id)).length,bad=roster.filter(x=>assets.get(x.id)?.status==='error');$('countLabel').textContent=roster.length+' FIGHTERS';$('loadStatus').textContent=bad.length?'Artwork unavailable: '+bad.map(x=>x.name).join(', '):good===roster.length?good+' fighters ready. V6.2 asset integrity pass loaded.':`Preparing artwork: ${good} / ${roster.length}`;$('retryButton').hidden=!bad.length;syncStage()
}
function makeStages(){let g=$('stageGrid');g.replaceChildren();for(let d of[{id:'random',name:'Random Stage',tag:'SURPRISE ME'},...stages]){let b=document.createElement('button');b.className='stage-card';b.dataset.stage=d.id;if(d.src){let i=new Image;i.src=resolveStageUrl(d.src);i.alt='';i.onerror=()=>{i.hidden=true;b.classList.add('stage-missing')};b.append(i)}else{let a=document.createElement('span');a.className='random-stage-art';a.textContent='?';b.append(a)}let c=document.createElement('span');c.className='stage-copy';c.innerHTML=`<strong>${d.name}</strong><small>${d.tag}</small>`;b.append(c);b.onclick=()=>{stage=d.id;save();syncStage();sound(260,.02)};g.append(b)}syncStage()}
function makeCards(){grid.replaceChildren();$('labFighter').replaceChildren();for(let d of roster){let b=document.createElement('button');b.className='fighter-card';b.dataset.id=d.id;b.setAttribute('aria-label',d.name);let c=document.createElement('canvas');c.width=c.height=140,c.setAttribute('aria-hidden','true');let n=document.createElement('strong');n.textContent=d.name,bs=document.createElement('span');bs.className='badges';for(let i=0;i<2;i++){let q=document.createElement('b');q.textContent='P'+(i+1);q.dataset.badge=i;bs.append(q)}let l=document.createElement('span');l.className='loading';l.textContent='LOADING';b.append(c,n,bs,l);if(d.v6New||d.v6Updated){let v=document.createElement('span');v.className='v6-badge';v.textContent=d.v6New?'NEW':'UPDATED';b.append(v)}b.onclick=()=>choose(d.id);grid.append(b);let o=document.createElement('option');o.value=d.id;o.textContent=d.name;$('labFighter').append(o)}sync()}
async function prep(d){assets.set(d.id,{status:'loading',def:d});let b=grid.querySelector(`[data-id="${d.id}"]`);try{let a=await loadFighter(d);assets.set(d.id,a);b.querySelector('canvas').getContext('2d').drawImage(a.portrait,0,0);b.querySelector('.loading').hidden=true}catch(e){assets.set(d.id,{status:'error',def:d,error:e.message});b.querySelector('.loading').textContent='ART UNAVAILABLE';console.warn(d.id,e)}sync()}
function start(){if(!pick.every(ready))return;arena.start(mode,pick.map(id=>assets.get(id)),$('difficulty').value,stage);$('selectScreen').hidden=true;$('matchScreen').hidden=false;$('practiceHint').hidden=mode!=='training';window.scrollTo(0,0);sound(550,.06)}
function menu(){arena.stop();$('matchScreen').hidden=true;$('selectScreen').hidden=false;$('pauseOverlay').hidden=$('resultOverlay').hidden=true;sync()}
function hud(g){if(!g.people)return;g.people.forEach((f,i)=>{let n=document.querySelector('.health.p'+(i+1)),bar=n.querySelector('.bar');$('name'+i).textContent=f.asset.def.name;bar.firstElementChild.style.width=f.hp+'%';bar.setAttribute('aria-valuenow',f.hp);n.querySelector('.hype i').style.width=f.meter+'%';n.querySelector('.round-dots').textContent=(g.wins[i]?'●':'○')+' '+(g.wins[i]>1?'●':'○')});$('clock').textContent=g.mode==='training'?'∞':String(Math.ceil(g.remaining/60)).padStart(2,'0');$('roundLabel').textContent=g.mode==='training'?'PRACTICE':'ROUND '+g.round;$('modeLabel').textContent=(g.mode==='cpu'?'VS CPU / '+g.difficulty.toUpperCase():g.mode==='local'?'LOCAL 2 PLAYER':'PRACTICE')+(g.venue?.name?' / '+g.venue.name.toUpperCase():'');$('pauseOverlay').hidden=!g.paused;let over=g.phase==='matchover';$('resultOverlay').hidden=!over;if(over)$('resultTitle').textContent=g.people[g.wins[0]>=2?0:1].asset.def.name+' takes the match'}
function phase(){if(reduced)return['idle',0,timing.idle];let n=tick%cycle;for(let s of sequences){if(n<timing[s])return[s,n,timing[s]];n-=timing[s]}return['idle',0,timing.idle]}
function drawOne(ctx,a,s,n,d,x,y,face){let g=a.frames[s]||a.frames.idle,i=Math.min(g.length-1,Math.floor(Math.min(.999,n/d)*g.length)),f=g[i],z=2*f.scale;ctx.save();ctx.imageSmoothingEnabled=false;ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(f.canvas,-f.px*z,-f.py*z,f.canvas.width*z,f.canvas.height*z);ctx.restore();return g.length}
function preview(){let[s,n,d]=phase();for(let i=0;i<2;i++){let p=$('preview'+i),c=p.querySelector('canvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#283041';x.beginPath();x.ellipse(150,230,88,10,0,0,Math.PI*2);x.stroke();let a=assets.get(pick[i]);if(a?.status==='ready'){let f=drawOne(x,a,s,n,d,150,229,i?-1:1),q=p.querySelector('.move-label');q.textContent=reduced?'IDLE':s.toUpperCase();p.querySelector('.anim-audit').textContent=`12/12 MOVES MAPPED / ${f} FRAMES${a.def.atlas?' / V6 ATLAS':''}`}else{x.fillStyle='#9ba6ba';x.textAlign='center';x.fillText('Preparing fighter...',150,145)}}}
function lab(){let a=assets.get($('labFighter').value);if(a?.status!=='ready')return;let s=$('labSequence').value,g=a.frames[s]||a.frames.idle,i=Math.floor(labTick/10)%g.length,f=g[i],c=$('labCanvas'),x=c.getContext('2d');x.fillStyle='#0c1120';x.fillRect(0,0,640,320);let z=f.scale*2.5;x.drawImage(f.canvas,320-f.px*z,290-f.py*z,f.canvas.width*z,f.canvas.height*z);$('labInfo').textContent=`${a.def.name} / ${s.toUpperCase()} / FRAME ${i+1} OF ${g.length}`;$('labNotes').textContent=a.def.notes||''}
for(let s of sequences){let o=document.createElement('option');o.value=s;o.textContent=s.toUpperCase();$('labSequence').append(o)}
$('labButton').onclick=()=>{$('labFighter').value=pick[slot];labTick=0;$('labDialog').showModal();lab()};$('helpButton').onclick=()=>$('helpDialog').showModal();$('labFighter').onchange=$('labSequence').onchange=()=>{labTick=0;lab()};$('labPlay').onclick=()=>{labPlay=!labPlay;$('labPlay').textContent=labPlay?'PAUSE':'PLAY'};$('labStep').onclick=()=>{labPlay=false;labTick+=10;lab()};$('muteButton').onclick=()=>{muted=!muted;setting();save()};$('motionButton').onclick=()=>{reduced=!reduced;setting();save()};$('startButton').onclick=start;$('menuButton').onclick=$('resultMenu').onclick=menu;$('rematchButton').onclick=start;$('pauseButton').onclick=$('resumeButton').onclick=()=>arena.pause();$('backButton').onclick=()=>arena.pause(true);for(let b of document.querySelectorAll('[data-slot]'))b.onclick=()=>{slot=+b.dataset.slot;sync()};for(let b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{mode=b.dataset.mode;for(let x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',x===b);sync()};$('randomButton').onclick=()=>{let p=roster.filter(x=>ready(x.id));if(p.length)choose(p[Math.floor(Math.random()*p.length)].id)};$('fighterSearch').oninput=()=>{let q=$('fighterSearch').value.toLowerCase(),n=0;for(let b of grid.children){b.hidden=!b.textContent.toLowerCase().includes(q);if(!b.hidden)n++}$('noResults').hidden=!!n};$('retryButton').onclick=()=>roster.filter(x=>assets.get(x.id)?.status==='error').forEach(prep);
const keys=new Set(CONTROL.flatMap(c=>Object.values(c)));addEventListener('keydown',e=>{if($('helpDialog').open||$('labDialog').open||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(arena.phase!=='off'){if(keys.has(e.code)||e.code==='Space')e.preventDefault();if((e.code==='KeyP'||e.code==='Escape')&&!e.repeat){arena.pause();return}if(e.code==='KeyR'&&mode==='training')return arena.reset();arena.key(e.code,true)}else{if(e.code==='Digit1'||e.code==='Digit2'){slot=e.code==='Digit1'?0:1;sync()}if(e.code==='Enter'&&!e.repeat)return start();let p=e.code.startsWith('Arrow')?1:0,o={KeyA:-1,ArrowLeft:-1,KeyD:1,ArrowRight:1,KeyW:-6,ArrowUp:-6,KeyS:6,ArrowDown:6}[e.code];if(o!==undefined){e.preventDefault();let ids=[...grid.children].filter(b=>!b.hidden).map(b=>b.dataset.id),cols=getComputedStyle(grid).gridTemplateColumns.split(' ').length,delta=Math.abs(o)===6?Math.sign(o)*cols:o,ix=Math.max(0,ids.indexOf(pick[p]));if(ids.length)choose(ids[(ix+delta+ids.length)%ids.length],p)}}});addEventListener('keyup',e=>arena.key(e.code,false));
let last=performance.now(),acc=0;function loop(now){acc+=Math.min(100,now-last);last=now;while(acc>=1000/60){tick++;arena.update();if($('labDialog').open&&labPlay)labTick++;acc-=1000/60}if(!$('selectScreen').hidden)preview();else arena.draw();if($('labDialog').open)lab();requestAnimationFrame(loop)}requestAnimationFrame(loop);setting();makeStages();
try{let[b,p]=await Promise.all([fetch(new URL('./tools/roster-v5.json',import.meta.url)),fetch(new URL('./tools/roster-v6.json',import.meta.url))]),base=await b.json(),patch=await p.json(),r=new Map(patch.replace.map(x=>[x.id,x]));roster=base.map(x=>r.get(x.id)||x);for(let x of patch.add)roster.push(x);makeCards();for(let d of [...roster].sort((a,b)=>+pick.includes(b.id)-+pick.includes(a.id))){await prep(d);await new Promise(r=>setTimeout(r,0))}}catch(e){$('loadStatus').textContent='Unable to load V6: '+e.message;console.error(e)}
window.SF={version:'6.2',snapshot:()=>arena.snapshot(),selection:()=>({pick:[...pick],mode,stage}),roster:()=>roster.map(d=>({id:d.id,name:d.name,status:assets.get(d.id)?.status,frames:assets.get(d.id)?.frames?Object.fromEntries(Object.entries(assets.get(d.id).frames).map(([k,v])=>[k,v.length])):{}})),stages:()=>stages};
