import {loadFighter,primeFighterSource,sequences} from './sprites-v6.js';
import {Arena,CONTROL,STAGE_DEFS,resolveStageUrl,retryStage} from './arena-v6.js';
import {getFighterBalance} from './combat-v6.js';
import {ArcadeAudio} from './audio-v6.js';
const VERSION='6.4',$=id=>document.getElementById(id),grid=$('fighterGrid'),assets=new Map(),loads=new Map(),audio=new ArcadeAudio();
const stageTags={'neon-laneway-beatdown':'MELBOURNE / NIGHT','backyard-bbq-bash':'AUSSIE SUBURB / SUNSET','construction-yard-throwdown':'CITY BUILD / SUNSET','arcade-food-court-frenzy':'MALL ARCADE / NEON','docklands-container-clash':'PORT / MIDNIGHT','outback-servo-showdown':'OUTBACK / GOLDEN HOUR'},stageDefs=STAGE_DEFS.map(x=>({...x,tag:stageTags[x.id]}));
const live=(text,urgent=false)=>{const n=$(urgent?'liveAssertive':'liveStatus');n.textContent='';requestAnimationFrame(()=>n.textContent=text)};
const arena=new Arena($('gameCanvas'),hud,n=>audio.play(n),t=>live(t,true),()=>togglePause());
let roster=[],pick=['lefty','bogan-tradie'],slot=0,mode='cpu',stage='neon-laneway-beatdown',muted=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,tick=0,labTick=0,labPlay=true,lastPaused=false,lastOver=false,lastSelectorFocus=null;
const portraitIds=['lefty','agenda','bimbo-babe','douchebag-dave','junkie','rapthug','killwoodrat','sk8r-boi','club-doll','grunge','yuppie','fat-gamer','influencer','yoga-mom','e-girl','cheerleader','punk-princess','neckbeard-nate','gym-bro','bogan-tradie'],portraitIndex=new Map(portraitIds.map((id,i)=>[id,i]));let portraitAtlas=null,portraitReady=false,portraitFailed=false,portraitUrl='';
const timing={idle:90,walk:84,jump:70,crouch:56,punch:58,kick:64,special:72,hurt:48,block:52,fall:68,getup:68,victory:96},cycle=sequences.reduce((a,s)=>a+timing[s],0);
try{const s=JSON.parse(localStorage.getItem('sf-v6')||'{}');muted=!!s.muted;if(typeof s.reduced==='boolean')reduced=s.reduced;if(s.stage==='random'||stageDefs.some(x=>x.id===s.stage))stage=s.stage}catch{}
const save=()=>{try{localStorage.setItem('sf-v6',JSON.stringify({muted,reduced,stage}))}catch{}};
const fighter=id=>roster.find(x=>x.id===id),ready=id=>assets.get(id)?.status==='ready';
function setting(){arena.reduced=reduced;audio.setMuted(muted);document.body.classList.toggle('reduced',reduced);$('muteButton').textContent='SOUND '+(muted?'OFF':'ON');$('muteButton').setAttribute('aria-pressed',String(muted));$('motionButton').textContent='REDUCED MOTION: '+(reduced?'ON':'OFF');$('motionButton').setAttribute('aria-pressed',String(reduced))}
function initials(n='?'){return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function portraitRect(id){const i=portraitIndex.get(id);return Number.isInteger(i)?[(i%5)*64,Math.floor(i/5)*64,64,64]:null}
function fallback(ctx,d,x,y,w,h){const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,'#1b2330');g.addColorStop(1,'#0e131d');ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.globalAlpha=.2;ctx.fillStyle=d?.accent||'#ffd36b';ctx.beginPath();ctx.arc(x+w/2,y+h*.42,w*.29,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=d?.accent||'#ffd36b';ctx.font=`700 ${Math.max(18,Math.floor(w*.24))}px monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(initials(d?.name),x+w/2,y+h*.43)}
function paintPortrait(ctx,d,x,y,w,h){const r=portraitRect(d?.id);if(portraitReady&&r){ctx.imageSmoothingEnabled=false;ctx.drawImage(portraitAtlas,...r,x,y,w,h);return true}fallback(ctx,d,x,y,w,h);return false}
function paintCards(){for(const b of grid.children){const d=fighter(b.dataset.id),c=b.querySelector('canvas');if(!d||!c)continue;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);paintPortrait(x,d,0,0,c.width,c.height)}}
async function loadPortraits(){portraitFailed=false;$('portraitRetry').hidden=true;try{const parts=await Promise.all([0,1,2,3].map(async i=>{const r=await fetch(new URL(`./assets/characters/portraits/roster-${i}.b64?v=${VERSION}`,import.meta.url));if(!r.ok)throw new Error(`portrait payload ${r.status}`);return r.text()})),s=parts.join('').replace(/\s+/g,''),raw=atob(s),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);if(portraitUrl)URL.revokeObjectURL(portraitUrl);portraitUrl=URL.createObjectURL(new Blob([bytes],{type:'image/webp'}));portraitAtlas=new Image();portraitAtlas.decoding='async';await new Promise((ok,no)=>{portraitAtlas.onload=ok;portraitAtlas.onerror=no;portraitAtlas.src=portraitUrl});portraitReady=true;paintCards();live('Fighter portraits ready.')}catch(e){portraitReady=false;portraitFailed=true;paintCards();$('portraitRetry').hidden=false;console.warn('Portrait atlas failed',e);live('Portrait atlas failed. Fallback fighter cards remain available. Retry portraits to try again.',true)}}
function stageDef(){return stageDefs.find(x=>x.id===stage)}function syncStage(){const d=stageDef(),name=d?.name||'Random Stage';$('stageChoice').textContent=$('venueName').textContent=name;for(const b of $('stageGrid').children)b.setAttribute('aria-pressed',String(b.dataset.stage===stage))}
function choose(id,n=slot){pick[n]=id;slot=n;lastSelectorFocus=grid.querySelector(`[data-id="${CSS.escape(id)}"]`);sync();const d=fighter(id);if(d&&!ready(id))prep(d);audio.play('menu')}
function sync(){for(let i=0;i<2;i++){const d=fighter(pick[i]);if(!d)continue;const p=$('preview'+i),a=assets.get(d.id),bal=getFighterBalance(d);p.classList.toggle('active',slot===i);p.querySelector('.slot-head').setAttribute('aria-pressed',String(slot===i));p.querySelector('em').textContent=slot===i?'SELECTING':'CHANGE';p.querySelector('h2').textContent=d.name;p.querySelector('.country').textContent=d.country;p.querySelector('.archetype').textContent=(bal.archetype+' · '+d.style).toUpperCase();p.querySelector('.bio').textContent=d.bio;p.querySelector('.signature strong').textContent=bal.specialName||d.special;const meters=p.querySelectorAll('meter');meters[0].value=d.speed||1;meters[1].value=d.defense||1;p.dataset.load=a?.status||'cold'}for(const b of grid.children){const id=b.dataset.id,p1=pick[0]===id,p2=pick[1]===id;b.classList.toggle('chosen1',p1);b.classList.toggle('chosen2',p2);b.setAttribute('aria-pressed',String(p1||p2));b.setAttribute('aria-label',fighter(id).name+(p1?' selected for Player 1':'')+(p2?' selected for Player 2':''));b.querySelector('[data-badge="0"]').hidden=!p1;b.querySelector('[data-badge="1"]').hidden=!p2}$('assignLabel').textContent='ASSIGNING TO P'+(slot+1);$('summaryNames').textContent=pick.map(id=>fighter(id)?.name||'Loading').join(' / VS / ');const errors=pick.filter(id=>assets.get(id)?.status==='error'),loading=pick.filter(id=>!ready(id)&&!errors.includes(id)),ok=pick.every(ready);$('startButton').disabled=!ok;$('startButton').textContent=ok?(mode==='training'?'START PRACTICE ↗':"LET'S FIGHT ↗"):'LOADING SELECTED MOVES...';$('difficultyLabel').hidden=mode!=='cpu';$('rulesLabel').textContent=mode==='training'?'Unlimited practice':'First to 2 rounds';$('rulesLabel').nextElementSibling.textContent=mode==='training'?'Full special meter':'60 second clock';$('countLabel').textContent=roster.length+' FIGHTERS';const cached=roster.filter(x=>ready(x.id)).length;if(errors.length)$('loadStatus').textContent='Move set unavailable: '+errors.map(id=>fighter(id)?.name||id).join(', ')+'. Retry or choose another fighter.';else if(loading.length)$('loadStatus').textContent='Loading combat atlas for '+loading.map(id=>fighter(id)?.name||id).join(' + ')+'.';else $('loadStatus').textContent=`20 portraits ready. ${cached} combat move set${cached===1?'':'s'} cached; remaining fighters load on demand.`;$('retryButton').hidden=!errors.length;syncStage()}
function makeCards(){grid.replaceChildren();$('labFighter').replaceChildren();for(const d of roster){const b=document.createElement('button');b.type='button';b.className='fighter-card';b.dataset.id=d.id;b.setAttribute('aria-pressed','false');const c=document.createElement('canvas');c.width=c.height=140;c.setAttribute('aria-hidden','true');fallback(c.getContext('2d'),d,0,0,140,140);const n=document.createElement('strong');n.textContent=d.name,bs=document.createElement('span');bs.className='badges';for(let i=0;i<2;i++){const q=document.createElement('b');q.textContent='P'+(i+1);q.dataset.badge=i;q.hidden=true;bs.append(q)}const l=document.createElement('span');l.className='loading';l.hidden=true;b.append(c,n,bs,l);const prime=()=>primeFighterSource(d);b.onpointerenter=prime;b.onfocus=prime;b.onpointerdown=prime;b.onclick=()=>choose(d.id);grid.append(b);const o=document.createElement('option');o.value=d.id;o.textContent=d.name;$('labFighter').append(o)}paintCards();sync()}
function makeStages(){const g=$('stageGrid');g.replaceChildren();for(const d of[{id:'random',name:'Random Stage',tag:'SURPRISE ME'},...stageDefs]){const b=document.createElement('button');b.type='button';b.className='stage-card';b.dataset.stage=d.id;b.setAttribute('aria-pressed','false');let img=null;if(d.src){img=new Image();img.decoding='async';img.loading='lazy';img.alt='';img.onerror=()=>{img.hidden=true;b.classList.add('stage-missing');live(`${d.name} image failed. Procedural fallback remains playable.`)};img.src=resolveStageUrl(d.src);b.append(img)}else{const a=document.createElement('span');a.className='random-stage-art';a.textContent='?';b.append(a)}const c=document.createElement('span');c.className='stage-copy';c.innerHTML=`<strong>${d.name}</strong><small>${d.tag}</small>`;b.append(c);b.onclick=()=>{if(b.classList.contains('stage-missing')&&d.src){retryStage(d.id);b.classList.remove('stage-missing');img.hidden=false;img.src=resolveStageUrl(d.src)+'?retry='+Date.now()}stage=d.id;save();syncStage();audio.play('menu')};g.append(b)}syncStage()}
async function prep(d){if(!d)return null;if(ready(d.id))return assets.get(d.id);if(loads.has(d.id))return loads.get(d.id);assets.set(d.id,{status:'loading',def:d});const b=grid.querySelector(`[data-id="${CSS.escape(d.id)}"]`);if(b){const l=b.querySelector('.loading');l.hidden=false;l.textContent='LOADING MOVES'}sync();const task=(async()=>{await new Promise(r=>requestAnimationFrame(r));const a=await loadFighter(d);assets.set(d.id,a);if(b)b.querySelector('.loading').hidden=true;sync();return a})().catch(e=>{assets.set(d.id,{status:'error',def:d,error:e.message});if(b){const l=b.querySelector('.loading');l.hidden=false;l.textContent='MOVE LOAD FAILED'}console.error('Fighter move set failed:',d.id,e);sync();live(`${d.name} combat move set failed. Other fighters remain playable.`,true);return null}).finally(()=>loads.delete(d.id));loads.set(d.id,task);return task}
const ensurePicked=()=>Promise.all(pick.map(id=>prep(fighter(id))));function scheduleWarm(){const run=()=>Promise.allSettled(roster.filter(x=>x.atlas&&!pick.includes(x.id)).slice(0,4).map(prep));if('requestIdleCallback'in window)requestIdleCallback(run,{timeout:2800});else setTimeout(run,1400)}
function start(){audio.unlock();if(!pick.every(ready)){ensurePicked();return}lastSelectorFocus=grid.querySelector(`[data-id="${CSS.escape(pick[slot])}"]`);arena.start(mode,pick.map(id=>assets.get(id)),$('difficulty').value,stage);$('selectScreen').hidden=true;$('matchScreen').hidden=false;$('practiceHint').hidden=mode!=='training';window.scrollTo(0,0);lastPaused=lastOver=false;requestAnimationFrame(()=>$('pauseButton').focus());audio.play('round-start')}
function menu(){arena.stop();$('matchScreen').hidden=true;$('selectScreen').hidden=false;$('pauseOverlay').hidden=$('resultOverlay').hidden=true;sync();requestAnimationFrame(()=>{(lastSelectorFocus&&document.contains(lastSelectorFocus)?lastSelectorFocus:$('startButton')).focus()})}
function setPaused(v){if(!arena.pause(v))return;if(v){audio.play('pause');requestAnimationFrame(()=>$('resumeButton').focus())}else requestAnimationFrame(()=>$('pauseButton').focus())}function togglePause(){if(arena.phase!=='off'&&arena.phase!=='matchover')setPaused(!arena.paused)}function rematch(){arena.rematch();$('resultOverlay').hidden=true;lastOver=false;requestAnimationFrame(()=>$('pauseButton').focus());audio.play('round-start')}
function hud(g){if(!g.people)return;g.people.forEach((f,i)=>{const n=document.querySelector('.health.p'+(i+1)),bar=n.querySelector('.bar'),m=n.querySelector('.hype');$('name'+i).textContent=f.asset.def.name;bar.firstElementChild.style.width=f.hp+'%';bar.setAttribute('aria-valuenow',String(Math.round(f.hp)));m.firstElementChild.style.width=f.meter+'%';m.setAttribute('aria-valuenow',String(Math.round(f.meter)));n.querySelector('.round-dots').textContent=(g.wins[i]?'●':'○')+' '+(g.wins[i]>1?'●':'○')});$('clock').textContent=g.mode==='training'?'∞':String(Math.ceil(g.remaining/60)).padStart(2,'0');$('roundLabel').textContent=g.mode==='training'?'PRACTICE':'ROUND '+g.round;$('modeLabel').textContent=(g.mode==='cpu'?'VS CPU / '+g.difficulty.toUpperCase():g.mode==='local'?'LOCAL 2 PLAYER':'PRACTICE')+(g.venue?.name?' / '+g.venue.name.toUpperCase():'');const paused=g.paused,over=g.phase==='matchover';$('pauseOverlay').hidden=!paused;$('resultOverlay').hidden=!over;if(over){const w=g.wins[0]>=2?0:1;$('resultTitle').textContent=g.people[w].asset.def.name+' TAKES THE MATCH'}if(paused&&!lastPaused)requestAnimationFrame(()=>$('resumeButton').focus());if(!paused&&lastPaused&&!over)requestAnimationFrame(()=>$('pauseButton').focus());if(over&&!lastOver)requestAnimationFrame(()=>$('rematchButton').focus());lastPaused=paused;lastOver=over}
function phase(){if(reduced)return['idle',0,timing.idle];let n=tick%cycle;for(const s of sequences){if(n<timing[s])return[s,n,timing[s]];n-=timing[s]}return['idle',0,timing.idle]}
function drawPreview(){const[s,n,dur]=phase();for(let i=0;i<2;i++){const p=$('preview'+i),c=p.querySelector('canvas'),x=c.getContext('2d'),a=assets.get(pick[i]),def=fighter(pick[i]);x.clearRect(0,0,c.width,c.height);if(a?.status==='ready'){const group=a.frames[s]||a.frames.idle,j=Math.min(group.length-1,Math.floor(Math.min(.999,n/dur)*group.length)),f=group[j],z=2*f.scale;x.save();x.translate(150,229);x.scale(i?-1:1,1);x.drawImage(f.canvas,-f.px*z,-f.py*z,f.canvas.width*z,f.canvas.height*z);x.restore();p.querySelector('.move-label').textContent=reduced?'IDLE':s.toUpperCase();p.querySelector('.anim-audit').textContent=`12/12 MOVES / ${group.length} FRAMES / COMPACT ATLAS`}else{paintPortrait(x,def,72,35,156,156);p.querySelector('.move-label').textContent=a?.status==='error'?'PORTRAIT':'READYING';p.querySelector('.anim-audit').textContent=a?.status==='error'?'RETRY MOVE SET':'MOVES LOAD ON DEMAND'}}}
function lab(){const a=assets.get($('labFighter').value),c=$('labCanvas'),x=c.getContext('2d');x.fillStyle='#0c1120';x.fillRect(0,0,640,320);if(a?.status!=='ready'){paintPortrait(x,fighter($('labFighter').value),240,70,160,160);return}const s=$('labSequence').value,g=a.frames[s]||a.frames.idle,i=Math.floor(labTick/10)%g.length,f=g[i],z=f.scale*2.5;x.drawImage(f.canvas,320-f.px*z,290-f.py*z,f.canvas.width*z,f.canvas.height*z);if($('labHitboxes').checked){const b=getFighterBalance(a.def);x.strokeStyle='#67d6ff';x.strokeRect(294,178,52,112);if(['punch','kick','special'].includes(s)){const m=b[s];x.strokeStyle='#ff5c78';x.strokeRect(320+m.hitbox.forward*.7,290-m.hitbox.up*.7,m.hitbox.w*.7,m.hitbox.h*.7)}}$('labInfo').textContent=`${a.def.name} / ${s.toUpperCase()} / FRAME ${i+1} OF ${g.length}`;$('labNotes').textContent=(a.def.notes||'')+` · ${getFighterBalance(a.def).archetype.toUpperCase()}`}
function trap(e){if(e.key!=='Tab')return;const o=!$('pauseOverlay').hidden?$('pauseOverlay'):!$('resultOverlay').hidden?$('resultOverlay'):null;if(!o)return;const f=[...o.querySelectorAll('button:not([disabled])')];if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}
const interactive=t=>t instanceof Element&&!!t.closest('button,a,input,select,textarea,dialog,[contenteditable="true"],[role="button"],[role="link"],[role="option"],[role="menuitem"],[role="slider"]'),combatKeys=new Set(CONTROL.flatMap(c=>Object.values(c)));
addEventListener('keydown',e=>{audio.unlock();trap(e);if($('helpDialog').open||$('labDialog').open)return;if(arena.phase!=='off'){if(combatKeys.has(e.code)||e.code.startsWith('Arrow'))e.preventDefault();if((e.code==='KeyP'||e.code==='Escape')&&!e.repeat){togglePause();return}if(e.code==='KeyR'&&mode==='training'&&!e.repeat){e.preventDefault();arena.resetTraining();return}arena.key(e.code,true);return}if(e.code==='Digit1'||e.code==='Digit2'){slot=e.code==='Digit1'?0:1;sync();return}if(e.code==='Enter'&&!e.repeat&&!interactive(e.target)&&pick.every(ready)){e.preventDefault();start()}});addEventListener('keyup',e=>arena.key(e.code,false));addEventListener('blur',()=>arena.clearInputs());document.addEventListener('visibilitychange',()=>{arena.clearInputs();if(document.hidden&&arena.phase!=='off'&&arena.phase!=='matchover'&&!arena.paused)setPaused(true)});
grid.addEventListener('keydown',e=>{if(!e.code.startsWith('Arrow'))return;const cards=[...grid.querySelectorAll('.fighter-card:not([hidden])')],i=cards.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const cols=Math.max(1,getComputedStyle(grid).gridTemplateColumns.split(' ').length),delta=e.code==='ArrowLeft'?-1:e.code==='ArrowRight'?1:e.code==='ArrowUp'?-cols:cols;cards[(i+delta+cards.length)%cards.length]?.focus()});
for(const b of document.querySelectorAll('[data-touch]')){const a=b.dataset.touch,release=e=>{arena.setVirtual(0,a,false);b.classList.remove('active');try{if(b.hasPointerCapture(e.pointerId))b.releasePointerCapture(e.pointerId)}catch{}};b.addEventListener('pointerdown',e=>{e.preventDefault();audio.unlock();b.setPointerCapture(e.pointerId);arena.setVirtual(0,a,true);b.classList.add('active')});for(const t of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(t,release)}
for(const s of sequences){const o=document.createElement('option');o.value=s;o.textContent=s.toUpperCase();$('labSequence').append(o)}
$('labButton').onclick=async()=>{$('labFighter').value=pick[slot];$('labDialog').showModal();await prep(fighter(pick[slot]));lab()};$('helpButton').onclick=()=>$('helpDialog').showModal();$('labFighter').onchange=async()=>{labTick=0;await prep(fighter($('labFighter').value));lab()};$('labSequence').onchange=()=>{labTick=0;lab()};$('labPlay').onclick=()=>{labPlay=!labPlay;$('labPlay').textContent=labPlay?'PAUSE':'PLAY';$('labPlay').setAttribute('aria-pressed',String(labPlay))};$('labStep').onclick=()=>{labPlay=false;$('labPlay').textContent='PLAY';$('labPlay').setAttribute('aria-pressed','false');labTick+=10;lab()};$('labHitboxes').onchange=()=>{arena.debugHitboxes=$('labHitboxes').checked;lab()};$('muteButton').onclick=()=>{muted=!muted;setting();save();if(!muted)audio.play('menu')};$('motionButton').onclick=()=>{reduced=!reduced;setting();save()};$('startButton').onclick=start;$('menuButton').onclick=$('backButton').onclick=$('resultMenu').onclick=menu;$('pauseButton').onclick=()=>setPaused(true);$('resumeButton').onclick=()=>setPaused(false);$('rematchButton').onclick=rematch;for(const b of document.querySelectorAll('[data-slot]'))b.onclick=()=>{slot=+b.dataset.slot;sync()};for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{mode=b.dataset.mode;for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));sync()};$('randomButton').onclick=()=>choose(roster[Math.floor(Math.random()*roster.length)].id);$('fighterSearch').oninput=()=>{const q=$('fighterSearch').value.toLowerCase().trim();let n=0;for(const b of grid.children){b.hidden=!b.textContent.toLowerCase().includes(q);if(!b.hidden)n++}$('noResults').hidden=!!n;live(n?`${n} fighters match the search.`:'No fighters match that search.')};$('retryButton').onclick=()=>pick.filter(id=>assets.get(id)?.status==='error').forEach(id=>{assets.delete(id);prep(fighter(id))});$('portraitRetry').onclick=loadPortraits;
async function loadRoster(){try{const r=await fetch(new URL(`./tools/roster-runtime-v6.json?v=${VERSION}`,import.meta.url));if(r.ok)return await r.json()}catch{}const[b,p]=await Promise.all([fetch(new URL(`./tools/roster-v5.json?v=${VERSION}`,import.meta.url)),fetch(new URL(`./tools/roster-v6.json?v=${VERSION}`,import.meta.url))]);if(!b.ok||!p.ok)throw new Error('Roster files unavailable');const base=await b.json(),patch=await p.json(),replace=new Map(patch.replace.map(x=>[x.id,x]));const r=base.map(x=>replace.get(x.id)||x);r.push(...patch.add);return r}
let last=performance.now(),acc=0;function loop(now){acc+=Math.min(100,now-last);last=now;while(acc>=1000/60){tick++;arena.update();if($('labDialog').open&&labPlay)labTick++;acc-=1000/60}if(!$('selectScreen').hidden)drawPreview();else arena.draw();if($('labDialog').open)lab();requestAnimationFrame(loop)}
setting();makeStages();loadPortraits();try{roster=await loadRoster();if(!Array.isArray(roster)||roster.length!==20||new Set(roster.map(x=>x.id)).size!==20)throw new Error(`Expected 20 unique fighters; got ${roster?.length||0}`);makeCards();await ensurePicked();sync();scheduleWarm();live('Stereotype Fighters ready.')}catch(e){console.error('Fatal roster failure',e);$('fatalError').hidden=false;$('fatalError').textContent='Fighter roster failed to load. Reload the page to retry.';live('Fighter roster failed to load. Reload to retry.',true)}requestAnimationFrame(loop);
window.SF={version:VERSION,snapshot:()=>arena.snapshot(),selection:()=>({pick:[...pick],mode,stage,difficulty:$('difficulty').value}),roster:()=>roster.map(d=>({id:d.id,name:d.name,atlas:d.atlas||null,status:assets.get(d.id)?.status||'on-demand',portrait:portraitReady?'ready':portraitFailed?'fallback':'loading',frames:assets.get(d.id)?.frames?Object.fromEntries(Object.entries(assets.get(d.id).frames).map(([k,v])=>[k,v.length])):{},balance:getFighterBalance(d)})),stages:()=>stageDefs,test:{loadAll:()=>Promise.all(roster.map(prep)),start,menu,pause:setPaused,resetTraining:()=>arena.resetTraining(),set:d=>arena.debugSet(d),debugHitboxes:v=>arena.debugHitboxes=!!v,clearInputs:()=>arena.clearInputs()}};
