import{loadFighter,primeFighterSource,drawSprite,sequences}from'./sprites-v6.js';
import{Arena,CONTROL,STAGE_DEFS,resolveStageUrl}from'./arena-v6.js';

const $=x=>document.getElementById(x),grid=$('fighterGrid'),assets=new Map(),loads=new Map(),arena=new Arena($('gameCanvas'),hud,sound);
const tags={'neon-laneway-beatdown':'MELBOURNE / NIGHT','backyard-bbq-bash':'AUSSIE SUBURB / SUNSET','construction-yard-throwdown':'CITY BUILD / SUNSET','arcade-food-court-frenzy':'MALL ARCADE / NEON','docklands-container-clash':'PORT / MIDNIGHT','outback-servo-showdown':'OUTBACK / GOLDEN HOUR'},stages=STAGE_DEFS.map(x=>({...x,tag:tags[x.id]}));
const timing={idle:90,walk:84,jump:70,crouch:56,punch:58,kick:64,special:72,hurt:48,block:52,fall:68,getup:68,victory:96},cycle=sequences.reduce((a,s)=>a+timing[s],0);
const portraitIds=['lefty','agenda','bimbo-babe','douchebag-dave','junkie','rapthug','killwoodrat','sk8r-boi','club-doll','grunge','yuppie','fat-gamer','influencer','yoga-mom','e-girl','cheerleader','punk-princess','neckbeard-nate','gym-bro','bogan-tradie'];
const portraitIndex=new Map(portraitIds.map((id,i)=>[id,i]));
const portraitAtlas=new Image();portraitAtlas.decoding='async';
let portraitReady=false,portraitFailed=false,portraitObjectUrl;
portraitAtlas.onload=()=>{portraitReady=true;portraitFailed=false;paintPortraitCards()};
portraitAtlas.onerror=()=>{portraitFailed=true;portraitReady=false;paintPortraitCards()};
async function loadPortraitAtlas(){try{let urls=[0,1,2,3].map(i=>new URL(`./assets/characters/portraits/roster-${i}.b64?v=6.4`,import.meta.url)),parts=await Promise.all(urls.map(async u=>{let r=await fetch(u);if(!r.ok)throw new Error('portrait payload '+r.status);return r.text()})),s=parts.join('').replace(/\s+/g,''),raw=atob(s),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);portraitObjectUrl=URL.createObjectURL(new Blob([bytes],{type:'image/webp'}));portraitAtlas.src=portraitObjectUrl}catch(e){portraitFailed=true;portraitReady=false;paintPortraitCards();console.warn('portrait atlas',e)}}
loadPortraitAtlas();

let roster=[],pick=['lefty','bogan-tradie'],slot=0,mode='cpu',stage='neon-laneway-beatdown',muted=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,tick=0,labTick=0,labPlay=true,audio;
try{let s={...JSON.parse(localStorage.getItem('sf-v5')||'{}'),...JSON.parse(localStorage.getItem('sf-v6')||'{}')};muted=!!s.muted;reduced=typeof s.reduced==='boolean'?s.reduced:reduced;if(s.stage==='random'||stages.some(x=>x.id===s.stage))stage=s.stage}catch{}
function save(){try{localStorage.setItem('sf-v6',JSON.stringify({muted,reduced,stage}))}catch{}}
function sound(f=300,d=.03){if(muted)return;try{audio||=new(window.AudioContext||window.webkitAudioContext);audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=f;g.gain.value=.045;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function ready(id){return assets.get(id)?.status==='ready'}
function fighter(id){return roster.find(x=>x.id===id)}
function setting(){arena.reduced=reduced;document.body.classList.toggle('reduced',reduced);$('motionButton').textContent='REDUCED MOTION: '+(reduced?'ON':'OFF');$('muteButton').textContent='SOUND '+(muted?'OFF':'ON')}
function choose(id,n=slot){pick[n]=id;slot=n;sync();let d=fighter(id);if(d&&!ready(id))prep(d);sound(370,.025)}
function stageDef(){return stages.find(x=>x.id===stage)}
function syncStage(){let d=stageDef(),name=d?.name||'Random Stage';$('stageChoice').textContent=$('venueName').textContent=name;for(let b of $('stageGrid').children)b.setAttribute('aria-pressed',b.dataset.stage===stage)}

function initials(name){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function portraitRect(id){let i=portraitIndex.get(id);return Number.isInteger(i)?[(i%5)*64,Math.floor(i/5)*64,64,64]:null}
function paintFallback(ctx,d,x,y,w,h){let g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,'#1b2330');g.addColorStop(1,'#0e131d');ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.globalAlpha=.18;ctx.fillStyle=d?.accent||'#ffd36b';ctx.beginPath();ctx.arc(x+w*.5,y+h*.42,w*.29,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=d?.accent||'#ffd36b';ctx.font=`700 ${Math.max(18,Math.floor(w*.24))}px Courier New`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(initials(d?.name||'?'),x+w/2,y+h*.43)}
function paintPortrait(ctx,d,x,y,w,h){let r=portraitRect(d?.id);if(portraitReady&&r){ctx.imageSmoothingEnabled=false;ctx.drawImage(portraitAtlas,...r,x,y,w,h);return true}paintFallback(ctx,d,x,y,w,h);return false}
function paintCardPortrait(canvas,d){let ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);paintPortrait(ctx,d,0,0,canvas.width,canvas.height);if(portraitFailed){ctx.fillStyle='#ffb0b0';ctx.font='7px Courier New';ctx.textAlign='center';ctx.fillText('PORTRAIT FALLBACK',canvas.width/2,canvas.height-7)}}
function paintPortraitCards(){for(let b of grid?.children||[]){let d=fighter(b.dataset.id),c=b.querySelector('canvas');if(d&&c)paintCardPortrait(c,d)}}

function sync(){
 for(let i=0;i<2;i++){let d=fighter(pick[i]);if(!d)continue;let p=$('preview'+i),a=assets.get(d.id);p.classList.toggle('active',slot===i);p.querySelector('.slot-head').setAttribute('aria-pressed',slot===i);p.querySelector('em').textContent=slot===i?'SELECTING':'CHANGE';p.querySelector('h2').textContent=d.name;p.querySelector('.country').textContent=d.country;p.querySelector('.archetype').textContent=d.style;p.querySelector('.bio').textContent=d.bio;p.querySelector('.signature strong').textContent=d.special;let m=p.querySelectorAll('meter');m[0].value=d.speed||1;m[1].value=d.defense||1;p.dataset.load=a?.status||'cold'}
 for(let b of grid.children){let id=b.dataset.id;b.classList.toggle('chosen1',pick[0]===id);b.classList.toggle('chosen2',pick[1]===id);b.querySelector('[data-badge="0"]').hidden=pick[0]!==id;b.querySelector('[data-badge="1"]').hidden=pick[1]!==id}
 $('assignLabel').textContent='ASSIGNING TO P'+(slot+1);$('summaryNames').textContent=pick.map(id=>fighter(id)?.name||'Loading').join('  / VS /  ');let selected=pick.map(id=>assets.get(id)?.status||'cold'),ok=selected.every(x=>x==='ready'),selectedErrors=pick.filter(id=>assets.get(id)?.status==='error'),selectedLoading=pick.filter(id=>!ready(id)&&!selectedErrors.includes(id));$('startButton').disabled=!ok;$('startButton').textContent=ok?(mode==='training'?'START PRACTICE  ↗':"LET'S FIGHT  ↗"):'LOADING SELECTED MOVES...';let opponent=$('opponentLabel');if(opponent)opponent.textContent=mode==='cpu'?'CPU OPPONENT':mode==='training'?'TRAINING PARTNER':'PLAYER 2';$('difficultyLabel').hidden=mode!=='cpu';$('rulesLabel').textContent=mode==='training'?'Unlimited practice':'First to 2 rounds';$('rulesLabel').nextElementSibling.textContent=mode==='training'?'Full special meter':'60 second clock';$('countLabel').textContent=roster.length+' FIGHTERS';let good=roster.filter(x=>ready(x.id)).length;if(selectedErrors.length)$('loadStatus').textContent='Move set unavailable: '+selectedErrors.map(id=>fighter(id)?.name||id).join(', ')+'. Portraits remain available; retry or choose another fighter.';else if(selectedLoading.length)$('loadStatus').textContent='Fighters are visible. Loading full move set for '+selectedLoading.map(id=>fighter(id)?.name||id).join(' + ')+'.';else $('loadStatus').textContent=`20 fighter portraits ready. ${good} full move set${good===1?'':'s'} cached; the rest load only when selected.`;$('retryButton').hidden=!selectedErrors.length;syncStage()
}
function makeStages(){let g=$('stageGrid');g.replaceChildren();for(let d of[{id:'random',name:'Random Stage',tag:'SURPRISE ME'},...stages]){let b=document.createElement('button');b.className='stage-card';b.dataset.stage=d.id;if(d.src){let i=new Image;i.decoding='async';i.loading='lazy';i.src=resolveStageUrl(d.src);i.alt='';i.onerror=()=>{i.hidden=true;b.classList.add('stage-missing')};b.append(i)}else{let a=document.createElement('span');a.className='random-stage-art';a.textContent='?';b.append(a)}let c=document.createElement('span');c.className='stage-copy';c.innerHTML=`<strong>${d.name}</strong><small>${d.tag}</small>`;b.append(c);b.onclick=()=>{stage=d.id;save();syncStage();sound(260,.02)};g.append(b)}syncStage()}
function makeCards(){grid.replaceChildren();$('labFighter').replaceChildren();for(let d of roster){let b=document.createElement('button');b.className='fighter-card';b.dataset.id=d.id;b.setAttribute('aria-label',d.name);let c=document.createElement('canvas');c.width=c.height=140;c.setAttribute('aria-hidden','true');paintCardPortrait(c,d);let n=document.createElement('strong');n.textContent=d.name;let bs=document.createElement('span');bs.className='badges';for(let i=0;i<2;i++){let q=document.createElement('b');q.textContent='P'+(i+1);q.dataset.badge=i;bs.append(q)}let l=document.createElement('span');l.className='loading';l.hidden=true;b.append(c,n,bs,l);if(d.v6New||d.v6Updated){let v=document.createElement('span');v.className='v6-badge';v.textContent=d.v6New?'NEW':'UPDATED';b.append(v)}let prime=()=>primeFighterSource(d);b.onpointerenter=prime;b.onfocus=prime;b.onpointerdown=prime;b.onclick=()=>choose(d.id);grid.append(b);let o=document.createElement('option');o.value=d.id;o.textContent=d.name;$('labFighter').append(o)}sync()}
async function prep(d){if(!d)return null;if(ready(d.id))return assets.get(d.id);if(loads.has(d.id))return loads.get(d.id);assets.set(d.id,{status:'loading',def:d});let b=grid.querySelector(`[data-id="${d.id}"]`);if(b){let l=b.querySelector('.loading');l.hidden=false;l.textContent='LOADING MOVES'}sync();let task=(async()=>{await new Promise(r=>requestAnimationFrame(()=>r()));let a=await loadFighter(d);assets.set(d.id,a);if(b){b.querySelector('.loading').hidden=true;b.classList.add('art-ready')}sync();return a})().catch(e=>{assets.set(d.id,{status:'error',def:d,error:e.message});if(b){let l=b.querySelector('.loading');l.hidden=false;l.textContent='MOVE LOAD FAILED'}console.warn(d.id,e);sync();return null}).finally(()=>loads.delete(d.id));loads.set(d.id,task);return task}
async function ensurePicked(){await Promise.all(pick.map(id=>prep(fighter(id))))}
function warmCompact(){let jobs=roster.filter(x=>x.atlas&&!pick.includes(x.id)).map(prep);Promise.allSettled(jobs).catch(()=>{})}
function scheduleWarm(){if('requestIdleCallback'in window)requestIdleCallback(warmCompact,{timeout:2200});else setTimeout(warmCompact,900)}
function start(){if(!pick.every(ready)){ensurePicked();return}arena.start(mode,pick.map(id=>assets.get(id)),$('difficulty').value,stage);$('selectScreen').hidden=true;$('matchScreen').hidden=false;$('practiceHint').hidden=mode!=='training';window.scrollTo(0,0);sound(550,.06)}
function menu(){arena.stop();$('matchScreen').hidden=true;$('selectScreen').hidden=false;$('pauseOverlay').hidden=$('resultOverlay').hidden=true;sync()}
function hud(g){if(!g.people)return;g.people.forEach((f,i)=>{let n=document.querySelector('.health.p'+(i+1)),bar=n.querySelector('.bar');$('name'+i).textContent=f.asset.def.name;bar.firstElementChild.style.width=f.hp+'%';bar.setAttribute('aria-valuenow',f.hp);n.querySelector('.hype i').style.width=f.meter+'%';n.querySelector('.round-dots').textContent=(g.wins[i]?'●':'○')+' '+(g.wins[i]>1?'●':'○')});$('clock').textContent=g.mode==='training'?'∞':String(Math.ceil(g.remaining/60)).padStart(2,'0');$('roundLabel').textContent=g.mode==='training'?'PRACTICE':'ROUND '+g.round;$('modeLabel').textContent=(g.mode==='cpu'?'VS CPU / '+g.difficulty.toUpperCase():g.mode==='local'?'LOCAL 2 PLAYER':'PRACTICE')+(g.venue?.name?' / '+g.venue.name.toUpperCase():'');$('pauseOverlay').hidden=!g.paused;let over=g.phase==='matchover';$('resultOverlay').hidden=!over;if(over)$('resultTitle').textContent=g.people[g.wins[0]>=2?0:1].asset.def.name+' takes the match'}
function phase(){if(reduced)return['idle',0,timing.idle];let n=tick%cycle;for(let s of sequences){if(n<timing[s])return[s,n,timing[s]];n-=timing[s]}return['idle',0,timing.idle]}
function drawOne(ctx,a,s,n,d,x,y,face){let g=a.frames[s]||a.frames.idle,i=Math.min(g.length-1,Math.floor(Math.min(.999,n/d)*g.length)),f=g[i],z=2*f.scale;ctx.save();ctx.imageSmoothingEnabled=false;ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(f.canvas,-f.px*z,-f.py*z,f.canvas.width*z,f.canvas.height*z);ctx.restore();return g.length}
function drawPortraitPreview(ctx,d,status){let size=156,x=(300-size)/2,y=35;ctx.fillStyle='#0d121d';ctx.fillRect(x-5,y-5,size+10,size+10);paintPortrait(ctx,d,x,y,size,size);ctx.strokeStyle=d?.accent||'#ffd36b';ctx.lineWidth=2;ctx.strokeRect(x-2,y-2,size+4,size+4);ctx.fillStyle=status==='error'?'#ffb0b0':'#9ba6ba';ctx.font='10px Courier New';ctx.textAlign='center';ctx.fillText(status==='error'?'MOVE SET UNAVAILABLE':'LOADING FULL MOVE SET…',150,213)}
function preview(){let[s,n,d]=phase();for(let i=0;i<2;i++){let p=$('preview'+i),c=p.querySelector('canvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#283041';x.beginPath();x.ellipse(150,230,88,10,0,0,Math.PI*2);x.stroke();let a=assets.get(pick[i]),def=fighter(pick[i]);if(a?.status==='ready'){let f=drawOne(x,a,s,n,d,150,229,i?-1:1),q=p.querySelector('.move-label');q.textContent=reduced?'IDLE':s.toUpperCase();p.querySelector('.anim-audit').textContent=`12/12 MOVES / ${f} FRAMES${a.def.atlas?' / STABLE ATLAS':''}`}else{drawPortraitPreview(x,def,a?.status);p.querySelector('.move-label').textContent=a?.status==='error'?'PORTRAIT':'READYING';p.querySelector('.anim-audit').textContent=a?.status==='error'?'PORTRAIT READY / RETRY MOVE SET':'PORTRAIT READY / MOVES LOAD ON DEMAND'}}}
function lab(){let a=assets.get($('labFighter').value),c=$('labCanvas'),x=c.getContext('2d');x.fillStyle='#0c1120';x.fillRect(0,0,640,320);if(a?.status!=='ready'){let d=fighter($('labFighter').value);paintPortrait(x,d,240,70,160,160);x.fillStyle='#9ba6ba';x.textAlign='center';x.font='14px Courier New';x.fillText('Loading full move set...',320,260);return}let s=$('labSequence').value,g=a.frames[s]||a.frames.idle,i=Math.floor(labTick/10)%g.length,f=g[i],z=f.scale*2.5;x.drawImage(f.canvas,320-f.px*z,290-f.py*z,f.canvas.width*z,f.canvas.height*z);$('labInfo').textContent=`${a.def.name} / ${s.toUpperCase()} / FRAME ${i+1} OF ${g.length}`;$('labNotes').textContent=a.def.notes||''}
async function loadLabFighter(){labTick=0;let d=fighter($('labFighter').value);lab();await prep(d);lab()}
for(let s of sequences){let o=document.createElement('option');o.value=s;o.textContent=s.toUpperCase();$('labSequence').append(o)}
$('labButton').onclick=async()=>{$('labFighter').value=pick[slot];labTick=0;$('labDialog').showModal();lab();await prep(fighter(pick[slot]));lab()};$('helpButton').onclick=()=>$('helpDialog').showModal();$('labFighter').onchange=loadLabFighter;$('labSequence').onchange=()=>{labTick=0;lab()};$('labPlay').onclick=()=>{labPlay=!labPlay;$('labPlay').textContent=labPlay?'PAUSE':'PLAY'};$('labStep').onclick=()=>{labPlay=false;labTick+=10;lab()};$('muteButton').onclick=()=>{muted=!muted;setting();save()};$('motionButton').onclick=()=>{reduced=!reduced;setting();save()};$('startButton').onclick=start;$('menuButton').onclick=$('resultMenu').onclick=menu;$('rematchButton').onclick=start;$('pauseButton').onclick=$('resumeButton').onclick=()=>arena.pause();$('backButton').onclick=()=>arena.pause(true);for(let b of document.querySelectorAll('[data-slot]'))b.onclick=()=>{slot=+b.dataset.slot;sync()};for(let b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{mode=b.dataset.mode;for(let x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',x===b);sync()};$('randomButton').onclick=()=>{if(!roster.length)return;let d=roster[Math.floor(Math.random()*roster.length)];choose(d.id)};$('fighterSearch').oninput=()=>{let q=$('fighterSearch').value.toLowerCase(),n=0;for(let b of grid.children){b.hidden=!b.textContent.toLowerCase().includes(q);if(!b.hidden)n++}$('noResults').hidden=!!n};$('retryButton').onclick=()=>pick.filter(id=>assets.get(id)?.status==='error').forEach(id=>prep(fighter(id)));
const keys=new Set(CONTROL.flatMap(c=>Object.values(c)));addEventListener('keydown',e=>{if($('helpDialog').open||$('labDialog').open||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(arena.phase!=='off'){if(keys.has(e.code)||e.code==='Space')e.preventDefault();if((e.code==='KeyP'||e.code==='Escape')&&!e.repeat){arena.pause();return}if(e.code==='KeyR'&&mode==='training')return arena.reset();arena.key(e.code,true)}else{if(e.code==='Digit1'||e.code==='Digit2'){slot=e.code==='Digit1'?0:1;sync()}if(e.code==='Enter'&&!e.repeat)return start();let p=e.code.startsWith('Arrow')?1:0,o={KeyA:-1,ArrowLeft:-1,KeyD:1,ArrowRight:1,KeyW:-6,ArrowUp:-6,KeyS:6,ArrowDown:6}[e.code];if(o!==undefined){e.preventDefault();let ids=[...grid.children].filter(b=>!b.hidden).map(b=>b.dataset.id),cols=getComputedStyle(grid).gridTemplateColumns.split(' ').length,delta=Math.abs(o)===6?Math.sign(o)*cols:o,ix=Math.max(0,ids.indexOf(pick[p]));if(ids.length)choose(ids[(ix+delta+ids.length)%ids.length],p)}}});addEventListener('keyup',e=>arena.key(e.code,false));
let last=performance.now(),acc=0;function loop(now){acc+=Math.min(100,now-last);last=now;while(acc>=1000/60){tick++;arena.update();if($('labDialog').open&&labPlay)labTick++;acc-=1000/60}if(!$('selectScreen').hidden)preview();else arena.draw();if($('labDialog').open)lab();requestAnimationFrame(loop)}requestAnimationFrame(loop);setting();makeStages();
try{let[b,p]=await Promise.all([fetch(new URL('./tools/roster-v5.json?v=6.4',import.meta.url)),fetch(new URL('./tools/roster-v6.json?v=6.4',import.meta.url))]),base=await b.json(),patch=await p.json(),r=new Map(patch.replace.map(x=>[x.id,x]));roster=base.map(x=>r.get(x.id)||x);for(let x of patch.add)roster.push(x);makeCards();sync();ensurePicked().then(sync);scheduleWarm()}catch(e){$('loadStatus').textContent='Unable to load V6.4: '+e.message;console.error(e)}
window.SF={version:'6.4',snapshot:()=>arena.snapshot(),selection:()=>({pick:[...pick],mode,stage}),roster:()=>roster.map(d=>({id:d.id,name:d.name,status:assets.get(d.id)?.status||'on-demand',portrait:portraitReady?'ready':portraitFailed?'fallback':'loading',frames:assets.get(d.id)?.frames?Object.fromEntries(Object.entries(assets.get(d.id).frames).map(([k,v])=>[k,v.length])):{}})),stages:()=>stages};
