import {drawSprite} from './sprites-v66.js';
import {CPU_LEVELS,HURTBOXES,getFighterBalance} from './combat-v66.js';

export const CONTROL=[
 {left:'KeyA',right:'KeyD',jump:'KeyW',down:'KeyS',block:'KeyE',punch:'KeyF',kick:'KeyG',special:'KeyH'},
 {left:'ArrowLeft',right:'ArrowRight',jump:'ArrowUp',down:'ArrowDown',block:'KeyI',punch:'KeyJ',kick:'KeyK',special:'KeyL'}
];
export const STAGE_DEFS=[
 {id:'neon-laneway-beatdown',name:'Neon Laneway Beatdown',src:'./assets/backgrounds/game/neon-laneway-beatdown.webp'},
 {id:'backyard-bbq-bash',name:'Backyard BBQ Bash',src:'./assets/backgrounds/game/backyard-bbq-bash.webp'},
 {id:'construction-yard-throwdown',name:'Construction Yard Throwdown',src:'./assets/backgrounds/game/construction-yard-throwdown.webp'},
 {id:'arcade-food-court-frenzy',name:'Arcade Food Court Frenzy',src:'./assets/backgrounds/game/arcade-food-court-frenzy.webp'},
 {id:'docklands-container-clash',name:'Docklands Container Clash',src:'./assets/backgrounds/game/docklands-container-clash.webp'},
 {id:'outback-servo-showdown',name:'Outback Servo Showdown',src:'./assets/backgrounds/game/outback-servo-showdown.webp'}
];
export const resolveStageUrl=src=>new URL(src,import.meta.url).href;
const FLOOR=446,GRAVITY=.65,W=960,H=540,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),overlaps=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const stages=new Map();
function loadStage(def,bust=''){let s=stages.get(def.id);if(!s){s={...def,image:null,ready:false,failed:false,url:resolveStageUrl(def.src)};stages.set(def.id,s)}if(typeof Image==='undefined')return s;const img=new Image();img.decoding='async';img.onload=()=>{s.image=img;s.ready=!!img.naturalWidth;s.failed=!s.ready};img.onerror=()=>{s.ready=false;s.failed=true;console.warn('Arena background failed:',s.url)};img.src=s.url+(bust?`?retry=${bust}`:'');s.image=img;return s}
for(const d of STAGE_DEFS)loadStage(d);export const retryStage=id=>{const d=STAGE_DEFS.find(x=>x.id===id);return d?loadStage(d,Date.now()):null};
class RNG{constructor(seed=0x51f15e){this.s=seed>>>0||1}next(){let x=this.s;x^=x<<13;x^=x>>>17;x^=x<<5;this.s=x>>>0;return this.s/4294967296}}
class Fighter{
 constructor(asset,side){this.asset=asset;this.side=side;this.balance=getFighterBalance(asset.def);this.x=side?700:260;this.y=FLOOR;this.vx=0;this.vy=0;this.face=side?-1:1;this.hp=100;this.meter=35;this.state='idle';this.tick=0;this.action=null;this.stun=0;this.buffer=null;this.think=0;this.plan={axis:0};this.intent={};this.armor=0}
 setState(s,game){if(this.state!==s){this.state=s;this.tick=0;if(game&&['jump','victory','fall','getup'].includes(s))game.playFighter(this,s)}}get grounded(){return this.y>=FLOOR-.1}
 hurtbox(){const b=!this.grounded?HURTBOXES.airborne:this.state==='crouch'?HURTBOXES.crouching:HURTBOXES.standing;return{x:this.x+b.x,y:this.y+b.y,w:b.w,h:b.h}}
 attackBox(m){const h=m.hitbox;return{x:this.face>0?this.x+h.forward:this.x-h.forward-h.w,y:this.y-h.up,w:h.w,h:h.h}}
 cpu(game,other){const c=CPU_LEVELS[game.difficulty]||CPU_LEVELS.normal,d=Math.abs(other.x-this.x),sign=Math.sign(other.x-this.x)||-this.face,b=this.balance;if(--this.think<=0){this.think=Math.floor(c.reaction[0]+game.random()*(c.reaction[1]-c.reaction[0]+1));const desired=b.archetype==='zoner'?205:b.archetype==='heavy'?92:b.archetype==='rushdown'?74:b.archetype==='defensive'?135:110;let axis=d>desired+25?sign:d<desired-24?-sign:0;if(game.random()<c.mistake)axis=game.random()<.5?-axis:0;const threatened=!!other.action||game.projectiles.some(p=>p.owner!==this.side&&Math.abs(p.x-this.x)<150),block=threatened&&d<185&&game.random()<c.defense,punish=other.action&&other.action.tick>other.action.move.startup+other.action.move.active&&d<145&&game.random()<c.punish;this.plan={axis,block,down:false,jump:d>150&&game.random()<.035};if(!block&&this.grounded){if(this.meter>=b.special.cost&&game.random()<c.special*(b.archetype==='zoner'?1.35:1))this.buffer={type:'special',ttl:8};else if(punish||game.random()<c.aggression*(d<150?1:.3))this.buffer={type:d<90&&game.random()<.58?'punch':'kick',ttl:8};if(d<68&&game.random()<c.retreat)this.plan.axis=-sign}}else this.plan.jump=false;return this.plan}
 collect(game,other){if(game.mode==='cpu'&&this.side===1)return this.cpu(game,other);const i=game.inputFor(this.side);for(const t of ['punch','kick','special'])if(i[t+'Pressed'])this.buffer={type:t,ttl:8};return i}
 startAction(type,game){const m=this.balance[type];if(!m||!this.grounded||type==='special'&&this.meter<m.cost)return false;if(type==='special')this.meter=clamp(this.meter-m.cost,0,100);this.action={type,move:{...m,hitbox:{...m.hitbox},projectile:m.projectile?{...m.projectile}:undefined},tick:0,hit:false,spawned:false};this.setState(type,game);this.armor=m.armor||0;game.playFighter(this,type);return true}
 advance(game,other,intent){this.intent=intent;this.tick++;if(this.buffer&&--this.buffer.ttl<0)this.buffer=null;if(this.hp<=0){this.action=null;this.setState('fall',game);this.vx*=.82;this.physics();return}if(this.stun>0){this.stun--;this.vx*=.8;this.physics();if(!this.stun){if(this.state==='fall'){this.setState('getup',game);this.stun=18}else this.setState('idle',game)}return}if(this.action){const a=this.action;a.tick++;this.vx*=.76;if(a.type==='special'&&a.move.kind==='dash'&&a.tick>=a.move.startup&&a.tick<a.move.startup+a.move.active)this.vx=this.face*(a.move.dash||4.8);if(a.type==='special'&&a.move.kind==='projectile'&&!a.spawned&&a.tick===a.move.startup){a.spawned=true;game.spawnProjectile(this,a.move)}if(a.tick>=a.move.startup+a.move.active+a.move.recovery){this.action=null;this.armor=0;this.setState(this.grounded?'idle':'jump',game)}}else{this.face=this.x<other.x?1:-1;if(intent.jump&&this.grounded&&!intent.block){this.vy=-this.balance.jump;this.setState('jump',game)}if(this.buffer&&!intent.block&&!intent.down&&this.grounded){if(this.startAction(this.buffer.type,game))this.buffer=null}if(!this.action){this.vx=(intent.block||intent.down)?0:intent.axis*this.balance.walk*(this.asset.def.speed||1);this.setState(!this.grounded||this.vy<0?'jump':intent.block?'block':intent.down?'crouch':intent.axis?'walk':'idle',game)}}const wasAir=!this.grounded;this.physics();if(wasAir&&this.grounded&&this.state==='jump'&&!this.action){this.setState('idle',game);this.stun=3}if(game.mode==='training')this.meter=100}
 physics(){this.vy+=GRAVITY;this.x=clamp(this.x+this.vx,55,905);this.y+=this.vy;if(this.y>=FLOOR){this.y=FLOOR;this.vy=0}}
 draw(ctx){const state=this.hp<=0?'fall':this.state,d=this.action?this.action.move.startup+this.action.move.active+this.action.move.recovery:({hurt:17,fall:34,getup:18}[state]||0);ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.ellipse(this.x,FLOOR+3,43,8,0,0,Math.PI*2);ctx.fill();drawSprite(ctx,this.asset,state,this.tick,this.x,this.y,1.95,this.face,d,this.vy)}
}
export class Arena{
 constructor(canvas,onChange=()=>{},soundSystem=null,announce=()=>{},pauseRequest=()=>{}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onChange=onChange;this.soundSystem=soundSystem;this.announce=announce;this.pauseRequest=pauseRequest;this.keys=new Set();this.pressed=new Set();this.virtualHeld=[new Set(),new Set()];this.virtualPressed=[new Set(),new Set()];this.gamepadHeld=[new Set(),new Set()];this.gamepadPressed=[new Set(),new Set()];this.gamepadPrev=[];this.gamepadProvider=()=>navigator.getGamepads?.()||[];this.phase='off';this.paused=false;this.tick=0;this.fx=[];this.projectiles=[];this.freeze=0;this.shake=0;this.reduced=false;this.debugHitboxes=typeof location!=='undefined'&&new URLSearchParams(location.search).get('debug')==='hitboxes';this.rng=new RNG()}
 random(){return this.rng.next()}playFighter(f,a){this.soundSystem?.playAction(f.asset.def.id,a).catch?.(()=>{})}
 async start(mode,assets,difficulty='normal',stageId=STAGE_DEFS[0].id,seed=0x51f15e){this.mode=mode;this.assets=assets;this.difficulty=difficulty;this.stageId=stageId;this.rng=new RNG(seed);const all=[...stages.values()];this.venue=stageId==='random'?all[Math.floor(this.random()*all.length)]:(stages.get(stageId)||all[0]);this.wins=[0,0];this.round=1;this.paused=false;this.clearInputs();this.resetRound(true);await this.soundSystem?.resume();await this.soundSystem?.playStageMusic(this.venue.id)}
 resetRound(first=false){this.people=this.assets.map((a,i)=>new Fighter(a,i));this.remaining=3600;this.phase=this.mode==='training'?'fight':'intro';this.phaseTick=0;this.fx=[];this.projectiles=[];this.freeze=0;this.shake=0;this.winner=null;this.roundReason='';this.clearInputs();if(this.mode==='training')this.people.forEach(f=>f.meter=100);this.onChange(this);if(!first)this.announce(this.mode==='training'?'Training reset':'Round '+this.round)}
 resetTraining(){if(this.mode==='training')this.resetRound()}rematch(){const v=this.venue;this.wins=[0,0];this.round=1;this.paused=false;this.clearInputs();this.venue=v;this.resetRound(true)}stop(){this.phase='off';this.paused=false;this.clearInputs();this.soundSystem?.stopStageMusic();this.onChange(this)}pause(v=!this.paused){if(this.phase==='off'||this.phase==='matchover')return false;const changed=this.paused!==!!v;this.paused=!!v;this.clearInputs();if(changed)this.onChange(this);return changed}
 key(code,down){if(down){if(!this.keys.has(code))this.pressed.add(code);this.keys.add(code)}else this.keys.delete(code)}clearInputs(){this.keys.clear();this.pressed.clear();for(const s of [...this.virtualHeld,...this.virtualPressed,...this.gamepadHeld,...this.gamepadPressed])s.clear()}setVirtual(side,a,down){const h=this.virtualHeld[side],p=this.virtualPressed[side];if(down){if(!h.has(a))p.add(a);h.add(a)}else h.delete(a)}inputFor(side){const c=CONTROL[side],held=a=>this.keys.has(c[a])||this.virtualHeld[side].has(a)||this.gamepadHeld[side].has(a),edge=a=>this.pressed.has(c[a])||this.virtualPressed[side].has(a)||this.gamepadPressed[side].has(a);return{axis:Number(held('right'))-Number(held('left')),jump:edge('jump'),down:held('down'),block:held('block'),punchPressed:edge('punch'),kickPressed:edge('kick'),specialPressed:edge('special')}}
 pollGamepads(){let pads=[];try{pads=[...(this.gamepadProvider()||[])].filter(Boolean).slice(0,2)}catch{return}for(let side=0;side<2;side++){const pad=pads[side],held=this.gamepadHeld[side],edge=this.gamepadPressed[side],prev=this.gamepadPrev[side]||new Set(),now=new Set();held.clear();edge.clear();if(pad){const ax=pad.axes?.[0]||0,ay=pad.axes?.[1]||0,b=i=>!!pad.buttons?.[i]?.pressed;if(ax<-.35||b(14))now.add('left');if(ax>.35||b(15))now.add('right');if(ay<-.45||b(12))now.add('jump');if(ay>.45||b(13))now.add('down');if(b(4)||b(5))now.add('block');if(b(0)||b(2))now.add('punch');if(b(1))now.add('kick');if(b(3)||b(6))now.add('special');if(b(9))now.add('menu');for(const a of now){held.add(a);if(!prev.has(a)){edge.add(a);if(a==='menu')this.pauseRequest()}}}this.gamepadPrev[side]=now}}
 spawnProjectile(f,m){const p=m.projectile;this.projectiles.push({owner:f.side,face:f.face,x:f.x+f.face*48,y:f.y-(p.y||100),vx:f.face*p.speed,life:p.life,w:p.w,h:p.h,move:{...m,kind:'projectile-hit'},color:f.asset.def.accent,hit:false})}
 attackEvents(){const ev=[];for(const f of this.people){const a=f.action;if(!a||a.hit||a.move.kind==='projectile'||a.tick<a.move.startup||a.tick>=a.move.startup+a.move.active)continue;const o=this.people[1-f.side],box=f.attackBox(a.move);if(overlaps(box,o.hurtbox())){a.hit=true;ev.push({attacker:f,defender:o,move:a.move,face:f.face})}}for(const p of this.projectiles){if(p.hit)continue;const o=this.people[1-p.owner],box={x:p.x-p.w/2,y:p.y-p.h/2,w:p.w,h:p.h};if(overlaps(box,o.hurtbox())){p.hit=true;ev.push({attacker:this.people[p.owner],defender:o,move:p.move,face:p.face})}}return ev}
 resolveHits(events){if(!events.length)return;const snap=this.people.map(f=>({state:f.state,face:f.face,block:!!f.intent.block,armor:f.armor}));let freeze=0;for(const e of events){const s=snap[e.defender.side],blocked=s.block&&s.face===-e.face&&!['fall','getup'].includes(s.state),armored=s.armor>0&&!blocked,damage=Math.max(1,Math.round(e.move.damage/(e.defender.balance.defense||1)*(blocked?.2:armored?.65:1)));e.defender.hp=Math.max(0,e.defender.hp-damage);e.attacker.meter=clamp(e.attacker.meter+(blocked?5:10),0,100);e.defender.meter=clamp(e.defender.meter+(blocked?4:7),0,100);if(!armored){e.defender.action=null;e.defender.buffer=null;e.defender.armor=0;e.defender.setState(blocked?'block':e.move.kind?.startsWith('projectile')||e.move.damage>=17?'fall':'hurt',this);e.defender.stun=blocked?e.move.blockStun:e.defender.state==='fall'?Math.max(30,e.move.hitStun):e.move.hitStun;e.defender.vx=e.face*e.move.knockback*(blocked?.4:1);e.defender.vy=blocked?0:e.defender.state==='fall'?-5.5:-1.8}freeze=Math.max(freeze,blocked?3:5);this.shake=Math.max(this.shake,blocked?1:4);this.burst(e.defender.x,e.defender.y-90,blocked?'#d7eeff':e.attacker.asset.def.accent,blocked?7:12);this.playFighter(e.defender,blocked?'block':'hurt')}this.freeze=Math.max(this.freeze,freeze)}
 separate(){const[a,b]=this.people,g=b.x-a.x;if(Math.abs(a.y-b.y)<80&&Math.abs(g)<65){const push=(65-Math.abs(g))/2,sign=g>=0?1:-1;a.x=clamp(a.x-sign*push,55,905);b.x=clamp(b.x+sign*push,55,905)}}burst(x,y,color,n){if(this.reduced)n=Math.min(4,n);for(let i=0;i<n;i++)this.fx.push({x,y,vx:(this.random()-.5)*9,vy:(this.random()-.6)*9,life:22,color})}
 finishRound(){const[a,b]=this.people,timeout=this.remaining<=0,double=a.hp<=0&&b.hp<=0;let winner=-1,reason;if(double)reason='double-ko';else if(timeout&&a.hp===b.hp)reason='time-draw';else{winner=a.hp===b.hp?-1:a.hp>b.hp?0:1;reason=timeout?'time':'ko'}this.winner=winner;this.roundReason=reason;this.phaseTick=0;this.projectiles=[];this.clearInputs();if(this.mode==='training'){this.phase='training-reset';this.people.forEach(p=>{p.action=null;p.buffer=null;if(p.hp<=0)p.setState('fall',this)});this.announce('Training knockout. Resetting.');this.onChange(this);return}this.phase='roundover';if(winner>=0)this.wins[winner]++;this.people.forEach((p,i)=>{p.action=null;p.buffer=null;p.stun=0;p.setState(winner>=0&&i===winner?'victory':'fall',this)});this.announce(reason==='double-ko'?'Double KO. Draw round.':reason==='time-draw'?'Time. Draw round.':`${reason==='time'?'Time. ':''}${this.people[winner].asset.def.name} wins round ${this.round}.`);this.onChange(this)}
 update(){this.pollGamepads();if(this.phase==='off'||this.paused){this.endFrame();return}this.tick++;this.phaseTick++;if(this.phase==='intro'){this.people.forEach(f=>f.tick++);if(this.phaseTick===1)this.announce('Round '+this.round);if(this.phaseTick===57)this.announce('Fight');if(this.phaseTick>=90){this.phase='fight';this.phaseTick=0;this.clearInputs()}}else if(this.phase==='fight'){if(this.freeze>0)this.freeze--;else{const[a,b]=this.people,intents=[a.collect(this,b),b.collect(this,a)];a.advance(this,b,intents[0]);b.advance(this,a,intents[1]);for(const p of this.projectiles){p.x+=p.vx;p.life--}this.projectiles=this.projectiles.filter(p=>p.life>0&&p.x>-80&&p.x<W+80&&!p.hit);this.resolveHits(this.attackEvents());this.separate();if(this.mode!=='training')this.remaining=Math.max(0,this.remaining-1);if(a.hp<=0||b.hp<=0||this.remaining<=0)this.finishRound()}}else if(this.phase==='roundover'||this.phase==='training-reset'){this.people.forEach(p=>{p.tick++;p.vx*=.8;p.physics()});const wait=this.phase==='training-reset'?45:105;if(this.phaseTick>=wait){if(this.mode==='training')this.resetRound();else if(this.wins.some(w=>w>=2)){this.phase='matchover';this.clearInputs();const w=this.wins[0]>=2?0:1;this.announce(this.people[w].asset.def.name+' wins the match');this.playFighter(this.people[w],'victory');this.onChange(this)}else{this.round++;this.resetRound()}}}else if(this.phase==='matchover')this.people.forEach(f=>f.tick++);this.fx=this.fx.filter(p=>--p.life>0);this.fx.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.12});this.shake*=.8;this.endFrame();if(this.tick%5===0)this.onChange(this)}endFrame(){this.pressed.clear();this.virtualPressed.forEach(s=>s.clear());this.gamepadPressed.forEach(s=>s.clear())}
 draw(){const c=this.ctx;c.save();if(!this.reduced&&this.shake>.3)c.translate(this.random()*this.shake-this.shake/2,0);this.drawStage(c);if(this.phase!=='off'){this.people.forEach(p=>p.draw(c));for(const p of this.projectiles){c.fillStyle=p.color;c.globalAlpha=.82;c.beginPath();c.arc(p.x,p.y,Math.max(p.w,p.h)/2,0,Math.PI*2);c.fill();c.globalAlpha=1}for(const p of this.fx){c.fillStyle=p.color;c.fillRect(p.x,p.y,4,4)}if(this.debugHitboxes)this.drawHitboxes(c)}c.restore();let banner='';if(this.phase==='intro')banner=this.phaseTick<57?'ROUND '+this.round:'FIGHT';if(this.phase==='roundover')banner=this.winner<0?(this.roundReason==='double-ko'?'DOUBLE KO':'DRAW'):this.people[this.winner].asset.def.name.toUpperCase()+' WINS';if(banner){c.fillStyle='rgba(7,10,18,.72)';c.fillRect(0,203,W,78);c.fillStyle='#ffe09a';c.textAlign='center';c.font='bold 34px system-ui';c.fillText(banner,W/2,253,880)}}
 drawHitboxes(c){c.save();c.lineWidth=2;for(const f of this.people){let b=f.hurtbox();c.strokeStyle='#67d6ff';c.strokeRect(b.x,b.y,b.w,b.h);if(f.action&&f.action.move.kind!=='projectile'&&f.action.tick>=f.action.move.startup&&f.action.tick<f.action.move.startup+f.action.move.active){b=f.attackBox(f.action.move);c.strokeStyle='#ff5c78';c.strokeRect(b.x,b.y,b.w,b.h)}}for(const p of this.projectiles){c.strokeStyle='#ffcf5a';c.strokeRect(p.x-p.w/2,p.y-p.h/2,p.w,p.h)}c.restore()}
 drawStage(c){const s=this.venue,img=s?.image;if(s?.ready&&img?.complete&&img.naturalWidth&&!s.failed){c.drawImage(img,0,0,W,H);return}const g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0c1225');g.addColorStop(.65,'#31364b');g.addColorStop(1,'#161a25');c.fillStyle=g;c.fillRect(0,0,W,H);c.fillStyle='#242332';c.fillRect(0,280,W,163);c.fillStyle='#444150';c.fillRect(0,441,W,8);c.fillStyle='#222734';c.fillRect(0,449,W,91)}
 snapshot(){return{phase:this.phase,paused:this.paused,round:this.round,wins:[...(this.wins||[])],remaining:this.remaining,freeze:this.freeze,winner:this.winner,roundReason:this.roundReason,venue:this.venue?.id,stageId:this.stageId,projectiles:this.projectiles.map(p=>({owner:p.owner,x:p.x,y:p.y,w:p.w,h:p.h})),people:(this.people||[]).map(f=>({id:f.asset.def.id,hp:f.hp,meter:f.meter,x:f.x,y:f.y,state:f.state,attack:f.action?.type||null,hurtbox:f.hurtbox()}))}}debugSet(d={}){if(!this.people)return;if(Array.isArray(d.hp))d.hp.forEach((v,i)=>this.people[i]&&(this.people[i].hp=v));if(Number.isFinite(d.remaining))this.remaining=d.remaining;if(d.positions)d.positions.forEach((v,i)=>this.people[i]&&(this.people[i].x=v));if(d.meter)d.meter.forEach((v,i)=>this.people[i]&&(this.people[i].meter=v));this.onChange(this)}
}
