// Compressed alpha-mask polygon data, generated by tools/build_mattes_v5.py.
import a from './matte-part-0.js';
import b from './matte-part-1.js';
import c from './matte-part-2.js';
import d from './matte-part-3.js';
export const encodedMattes=a+b+c+d;
