export const sequences=['idle','walk','jump','crouch','punch','kick','special','hurt','block','fall','getup','victory'];
const CELL=64,COLS=5,assetCache=new Map();
const surface=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
const loadImage=src=>new Promise((resolve,reject)=>{const i=new Image();i.decoding='async';i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Unable to load image: '+src));i.src=src});
let portraitSheetPromise;function portraitSheet(){return portraitSheetPromise??=(async()=>{const parts=await Promise.all([0,1,2,3].map(async i=>{const r=await fetch(new URL(`./assets/characters/portraits/roster-${i}.b64`,import.meta.url));if(!r.ok)throw Error('Portrait chunk unavailable');return r.text()})),raw=atob(parts.join('').replace(/\s/g,'')),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return loadImage(URL.createObjectURL(new Blob([bytes],{type:'image/webp'})))})()}
export async function loadRosterPortrait(index){const sheet=await portraitSheet(),c=surface(CELL,CELL);c.getContext('2d').drawImage(sheet,(index%COLS)*CELL,Math.floor(index/COLS)*CELL,CELL,CELL,0,0,CELL,CELL);return c}
function trim(c,ax=c.width/2,ay=c.height){const w=c.width,h=c.height,d=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h).data;let l=w,t=h,r=-1,b=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>8){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}if(r<l)return{canvas:c,px:ax,py:ay,scale:1};const o=surface(r-l+1,b-t+1);o.getContext('2d').drawImage(c,l,t,o.width,o.height,0,0,o.width,o.height);return{canvas:o,px:ax-l,py:ay-t,scale:1}}
function atlasCell(img,index,[w,h],cols){const c=surface(w,h);c.getContext('2d').drawImage(img,(index%cols)*w,Math.floor(index/cols)*h,w,h,0,0,w,h);return trim(c,w/2,h)}
const median=a=>{const b=[...a].sort((x,y)=>x-y);return b[Math.floor(b.length/2)]||1};
function normalize(frames){const idle=median(frames.idle.map(f=>f.canvas.height)),base=104/idle;for(const[s,list]of Object.entries(frames)){const mh=median(list.map(f=>f.canvas.height)),scale=['punch','kick','special','hurt','block','victory'].includes(s)?104/Math.max(idle*.85,Math.min(idle*1.18,mh)):base;for(const f of list)f.scale=scale}}
function atlasUrl(def){if(def.atlas?.startsWith('./')||def.atlas?.includes('/'))return new URL(def.atlas,import.meta.url).href;return new URL('./assets/characters/v66/'+def.atlas,import.meta.url).href}
async function loadAtlasAsset(def){const portrait=await loadRosterPortrait(def.rosterPortraitIndex??def.portraitIndex),img=await loadImage(atlasUrl(def)),[cw,ch]=def.atlasCell||[],cols=def.atlasColumns||8;if(!cw||!ch||img.naturalWidth%cw||img.naturalHeight%ch||img.naturalWidth/cw!==cols)throw Error(`${def.name} compact atlas grid mismatch`);const frames={};let cursor=0,total=0;for(const s of sequences){const n=def.atlasCounts?.[s]||0;if(!n)throw Error(`${def.name} compact atlas missing ${s}`);total+=n;frames[s]=Array.from({length:n},()=>atlasCell(img,cursor++,[cw,ch],cols))}const cap=(img.naturalWidth/cw)*(img.naturalHeight/ch);if(total>cap)throw Error(`${def.name} compact atlas has ${cap} cells for ${total} frames`);normalize(frames);return{def,portrait,frames,renderMode:'atlas',status:'ready'}}
async function loadPuppetAsset(def){const portrait=await loadRosterPortrait(def.rosterPortraitIndex??def.portraitIndex);return{def,portrait,renderMode:'puppet',status:'ready'}}
export function primeFighterSource(def){if(assetCache.has(def.id))return assetCache.get(def.id);const p=(def.render==='atlas'&&def.atlas?loadAtlasAsset(def):loadPuppetAsset(def)).catch(error=>{assetCache.delete(def.id);throw error});assetCache.set(def.id,p);return p}export const loadFighter=primeFighterSource;export const retryFighter=def=>{assetCache.delete(def.id);return primeFighterSource(def)};
function pose(asset,state,tick,duration=0,vy=0){if(state==='landing')state='crouch';const g=asset.frames[state]||asset.frames.idle;if(state==='jump'){const i=vy<-4?Math.min(1,g.length-1):vy>4?Math.max(0,g.length-2):Math.floor(g.length/2);return g[i]}if(state==='fall'&&duration)return g[Math.min(g.length-1,Math.floor(tick/Math.max(1,duration)*g.length))];const speed=state==='walk'?4:state==='idle'?7:5;return g[Math.floor(tick/speed)%g.length]}
function drawPuppet(ctx,asset,state,tick,x,y,size=1,face=1,vy=0){const a=asset.def.accent||'#5ec8ff',bob=state==='idle'?Math.sin(tick*.14)*2:state==='walk'?Math.sin(tick*.55)*4:0,crouch=state==='crouch'?.78:1;ctx.save();ctx.translate(Math.round(x),Math.round(y+bob));ctx.scale(face,1);ctx.strokeStyle='#111827';ctx.lineWidth=7*size;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-8,-55*crouch);ctx.lineTo(-13,-10);ctx.moveTo(8,-55*crouch);ctx.lineTo(13,-10);ctx.stroke();ctx.fillStyle=a;ctx.strokeStyle='#10131d';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-18,-105*crouch,36,54*crouch,8);ctx.fill();ctx.stroke();ctx.strokeStyle='#243042';ctx.lineWidth=7;const reach=state==='punch'?48:state==='special'?58:25,kick=state==='kick'?43:0;ctx.beginPath();ctx.moveTo(-15,-94*crouch);ctx.lineTo(-25,-64*crouch);ctx.moveTo(15,-94*crouch);ctx.lineTo(reach,-75*crouch);if(kick){ctx.moveTo(8,-55*crouch);ctx.lineTo(kick,-38)}ctx.stroke();ctx.beginPath();ctx.arc(0,-125*crouch+(state==='jump'?-Math.max(0,-vy*2):0),18,0,Math.PI*2);ctx.clip();if(asset.portrait)ctx.drawImage(asset.portrait,-18,-143*crouch,36,36);else{ctx.fillStyle='#ddd';ctx.fill()}ctx.restore()}
export function drawSprite(ctx,asset,state,tick,x,y,size=1,face=1,duration=0,vy=0){if(!asset||asset.status!=='ready')return;if(asset.renderMode!=='atlas'){drawPuppet(ctx,asset,state,tick,x,y,size,face,vy);return}const f=pose(asset,state,tick,duration,vy),s=size*f.scale;ctx.save();ctx.imageSmoothingEnabled=false;ctx.translate(Math.round(x),Math.round(y));ctx.scale(face,1);ctx.drawImage(f.canvas,Math.round(-f.px*s),Math.round(-f.py*s),Math.round(f.canvas.width*s),Math.round(f.canvas.height*s));ctx.restore()}
